insert into category (description) values ('American')
insert into category (description) values ('Indian')
insert into category (description) values ('Western')
insert into category (description) values ('Thai')

insert into unit_of_measure (description) values ('Spoon')
insert into unit_of_measure (description) values ('Ounce')
insert into unit_of_measure (description) values ('Pinch')
insert into unit_of_measure (description) values ('Cup')
insert into unit_of_measure (description) values ('Dash')
insert into unit_of_measure (description) values ('Each')
insert into unit_of_measure (description) values ('Pint')
insert into unit_of_measure (description) values ('Teaspoon')
insert into unit_of_measure (description) values ('Tablespoon')